### ISSUE TITLE
require compute_hash_on_elements helper function

### ISSUE THREAD

**Issue by script-money** [foundry-rs/starknet-foundry#1286]
### Which component is your feature related to?

Forge

### Feature Request

While writing tests related to signatures, I discovered in TxInfoMockTrait, I need to separately calculate and add the transaction_hash using the other SDK, like Starknet.js. Those SDKs accepts a message array and then calculates the hash, as seen in [signatureTestV5.ts](https://github.com/PhilippeR26/starknet.js-workshop-typescript/blob/main/src/scripts/signature/2.signatureTestV5.ts) or [utils.py](https://github.com/software-mansion/starknet.py/blob/1859b5d2d2be9963c2fa178567cc2ba82a282823/starknet_py/hash/utils.py#L42). I think that the compute_hash_on_elements helper function should be integrated into snforge for greater ease of use.

I should be able to submit a pull request to add the relevant function into snforge_std/src/signature.

**Comment by Arcticae** [comment]
@script-money it is recommended to always use the native counterpart in order to achieve end means, in this case i think corelib is the answer:
https://github.com/starkware-libs/cairo/blob/a4e7753f73b9731fe08c50a2f3af2b39e11ae657/corelib/src/pedersen.cairo#L13C13-L13C13

If you'd like to extend it, please do submit a contribution there. We will probably not want to accept that since it's not the use case of snforge to provide those implementations.

However if you feel that the documentation is lacking - please let me know under this issue and i will create another one
