### ISSUE TITLE
Consider implementing wrapper for `store` for ERC20 balance increase

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#1461]
Sth like `fn increase_balance(erc20_addr, contract_addr)`. We should check if ERC20 standard enforces internal storage names for balance data, otherwise this task is not relevant imo (since we wouldn't know what is the storage var name we want to write the balance under).

**Comment by Arcticae** [comment]
I think this is waaay too specific for the level we operate on
Is this something that was requested? 
Ideally as a contract developer i would just implement an util myself in my project for this

**Comment by piotmag769** [comment]
@Arcticae was requrested by @enitrat

**Comment by enitrat** [comment]
The OZ implementation uses ERC20_balances as a storage variable name. I think a `fn deal(address, amount)` would be nice to have

**Comment by Arcticae** [comment]
@enitrat we discussed with the team and this is something that we consider adding to docs as an example, but we won't be implementing it into `snforge_std` since maintaining compatibility with different contract versions would add on to our constant workload. Moreover, this should be easy enough for the user to make a helper for in own project (people depend on different standards as well).
