### ISSUE TITLE
Offload all possible errors to cairo

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1896]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

All runner errors should be replaced with errors on cairo-level (result or panic)

Rust panic should occur only when we have done something wrong (implementation-wise)

@piotmag769 please provide a broader description 🙏

**Comment by piotmag769** [comment]
After doing this task we shouldn't throw any errors from our implementations of `HintProcessor` (our runtimes), especially in `execute_cheatcode_hint` function, we should instead write the result to the cairo memory and then panic in cairo or change some signatures and let user handle the result.

Things may get tricky for hints we don't handle by ourselves i.e. these that are handled by `StarknetRuntime` (the lowest layer that uses blockifier's `SyscallHintProcesor` to handle the hints), since we don't control the errors thrown there. I don't think there is a clear solution for that so we will still have to catch those errors here

https://github.com/foundry-rs/starknet-foundry/blob/b458b753e9e6e2f69703da0aafc917230c2b237a/crates/forge-runner/src/running.rs#L302
