### ISSUE TITLE
Add support for numbers in multicall

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#2245]
### Description

It seems counterintuitive not to allow raw integers inputs in the mutlicall, right now it's not supported and only string inputs are accepted

**Example:**

```
[[call]]
call_type = "deploy"
class_hash = "0x076e94149fc55e7ad9c5fe3b9af570970ae2cf51205f8452f39753e9497fe849"
inputs = []
id = "map_contract"
unique = false

[[call]]
call_type = "invoke"
contract_address = "map_contract"
function = "put"
inputs = ["0x123", "234"]
```

### Desired Behavior

We can allow the `inputs` to be array of numbers:

```
...
[[call]]
call_type = "invoke"
contract_address = "map_contract"
function = "put"
inputs = [123, 0x234]
```

Also `contract_address` and `class_hash` can be numbers,
Example:

```
[[call]]
call_type = "deploy"
class_hash = 0x076e94149fc55e7ad9c5fe3b9af570970ae2cf51205f8452f39753e9497fe849"
inputs = []
id = "map_contract"
unique = false
```

### Context
- [Path to the file that needs altering](https://github.com/foundry-rs/starknet-foundry/blob/bc608465bc72b1c84648bbae6558182deccd9e35/crates/sncast/src/starknet_commands/multicall/run.rs#L4)
- [Multicall docs](https://foundry-rs.github.io/starknet-foundry/starknet/multicall.html)
- [Numbers in TOML format](https://toml.io/en/)

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry2).

### My background and how it can be leveraged
I'm Joseph a blockchain developer with over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Begin by studying the codebase to ensure design consistency, then proceed to work on the task.

1. Study current codebase design
2. Identify parts of code that needs to be changed
3. Make necessary changes
4. Add tests to make sure the changes are working and no adverse effects
5. And lastly optimize

**Comment by kfastov** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I'm a Full Stack Web3 Developer with experience in Rust and Cairo and participated in ODHacks since 2.0, working as both a contributor and maintainer. 
I am also using starknet-foundry in my own projects and familiar with different features and would be happy to help

### How I plan on tackling this issue
I would define a new [untagged] enum for the `Input` type with two options: one for String and one for number (will determine the correct type later). Then I'll use this type in `DeployCall` and `InvokeCall` for its `inputs` field instead of String. Then I'll update tests, including different edge cases, like invalid numbers, large numbers and so on

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
i have experience in cairo and blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution.

### How I plan on tackling this issue
I'll enhance the multicall configuration by implementing a custom TOML deserializer that intelligently handles both string and numeric inputs, automatically detects and converts hexadecimal/decimal formats for all numeric fields (class_hash, contract_address, inputs), while maintaining backward compatibility with existing string inputs. This allows for a more intuitive developer experience without breaking existing configurations.
