### ISSUE TITLE
Remove `RawForgeConfig` abstraction

### ISSUE THREAD

**Issue by kkawula** [foundry-rs/starknet-foundry#2514]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

Config got from `Scarb.toml` is stored in `ForgeConfigFromScarb` struct, but firstly toml is mapped into `RawForgeConfig`, partially validated, and then mapped into `ForgeConfigFromScarb`. It can be done without `RawForgeConfig` abstraction by implementing `Deserialize Trait` for `ForgeConfigFromScarb`, `ForkTarget`, and so on. 

Flow that should be refactored: https://github.com/foundry-rs/starknet-foundry/blob/3d857eb9cca98e34c1d21ffd167d56d031b51264/crates/forge/src/scarb.rs#L26-L31

Validation for `ForkTarget` that should be implemented in the deserialize method: https://github.com/foundry-rs/starknet-foundry/blob/3d857eb9cca98e34c1d21ffd167d56d031b51264/crates/forge/src/scarb/config.rs#L91-L115
`ForkTarget::new` should be replaced, by creation from deserializing json.

**Comment by 0xNeshi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry2).

### My background and how it can be leveraged
Rust experience and a regular Foundry user for Starknet smart contract testing. As a regular Foundry user, I'm very interested in making it as efficient and as clean as possible.

### How I plan on tackling this issue
Just as described in the Description section of the issue, the necessary changes are clear enough. One thing to note for redundancy is that tests should be updated as well.

**Comment by bloomingpeach** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry2).

### My background and how it can be leveraged
I'm a Web3 Developer with experience in Rust and Cairo. I have participated since ODHack 7.0, and have contributed to various open sources projects: Raito, Shinigami, BeaconKit,...

 I take responsibility to all my assigned work and try to finish it quickly with the best result, and I also communicate/collaborate with maintainers well. 


### How I plan on tackling this issue
I will follow the description and implement the required code, and I will update my progress frequently to ensure going in right direction and save time for both maintainer and mine.

**Comment by DanielEmmanuel1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hello again, my name is Deon, I'm a Full-Stack web3 developer with a passion for building efficient and reliable software. I have experience in various Rust ecosystems and enjoy tackling challenges that improve code quality and user experience. 

My background includes working on open-source projects OD Hack included, as well as contributing to community discussions, and continuously learning about the latest advancements in Rust.

### How I plan on tackling this issue
- I will start by examining the existing mapping process from Scarb.toml to RawForgeConfig and then to ForgeConfigFromScarb to understand the flow and the validations currently in place.

- I will then refactor the ForgeConfigFromScarb, ForkTarget, and any related structs to implement the Deserialize trait directly. This will streamline the mapping process by allowing the deserialization of the TOML configuration directly into the target struct.

- Next will be to eliminate the RawForgeConfig abstraction from the process, ensuring that the code correctly handles the deserialization and any necessary validations directly within ForgeConfigFromScarb.

- Finally I will create unit tests to validate the new deserialization logic and ensure that edge cases and potential parsing errors are handled gracefully, then update any relevant documentation to reflect the changes made to the configuration handling process, including any new usage patterns.

- Once everything is tested and documented, I’ll then submit a pull request with the changes, detailing the improvements and any impact on existing functionality.

Once again, I’m ecstatic about the opportunity of contributing to the Foundry project and can’t wait to hop right on it.

**Comment by khayss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I’m a Rust developer with strong experience in refactoring and simplifying code structures. I’ve worked on several projects where I focused on streamlining abstractions and improving code clarity and performance. My familiarity with Rust’s trait system, including implementing `Deserialize` for custom structs, makes me a great fit for this refactoring task.

### How I plan on tackling this issue
To remove the `RawForgeConfig` abstraction and refactor the process of handling the config from `Scarb.toml`, I will:

1. Implement the `Deserialize` trait directly for `ForgeConfigFromScarb`, `ForkTarget`, and any other relevant structs.
2. Update the config parsing process so that `Scarb.toml` is deserialized directly into `ForgeConfigFromScarb`, bypassing the intermediate `RawForgeConfig` step.
3. Ensure the existing validation logic is preserved or incorporated into the new deserialization flow.
4. Test the refactored code to confirm it works as expected, ensuring there are no regressions in functionality or validation.
5. Review the impact of the change on code readability and performance to confirm it achieves the intended simplification.

I’m excited to contribute to this refactoring effort and would love to be considered for this issue.

**Comment by bloomingpeach** [comment]
> Hey @bloomingpeach how's the progress on this?

Hi, I will try to finish this weekend, sorry for the inactive
