### ISSUE TITLE
Make errors thrown during data transformation more descriptive

### ISSUE THREAD

**Issue by integraledelebesgue** [foundry-rs/starknet-foundry#2554]
## Component the issue is related to
Cast - data transformer

## Issue
Before introducing calldata transformation, commands used to throw quite verbose errors concerning e.g. absence of the requested class hash. They originated from blockifier.
Since transformer was introduced, such errors are thrown earlier in the execution process and are less descriptive

I added a workaround for preserving old error messages despite throwing them from completely different place. `ContractError`s normally obtained *after* sending transaction to chain are created [here](https://github.com/foundry-rs/starknet-foundry/blob/bd568166c8636ef7d0f80b179f9de44f9efef77e/crates/sncast/src/lib.rs#L278) and [here](https://github.com/foundry-rs/starknet-foundry/blob/bd568166c8636ef7d0f80b179f9de44f9efef77e/crates/sncast/src/lib.rs#L478) to mimic the old behaviour.

This isn't a nice solution though. Maybe we should rethink our error propagation logic and perform a revamp.

**Comment by cptartur** [comment]
@integraledelebesgue please update this

**Comment by cptartur** [comment]
I think we could at least retain behavior similar to older errors we had. 

E.g. (as of writing this) instead of an error like that `error: An error occurred in the called contract[..]Class with hash[..]is not declared[..]` we now throw `"Error: Couldn't retrieve contract class with hash:`.

However, the RPC endpoint used to get contract class (and so an ABI) is throwing a very descriptive error https://github.com/starkware-libs/starknet-specs/blob/6d88b7399f56260ece3821c71f9ce53ec55f830b/api/starknet_api_openrpc.json#L522 in a case where contract is missing: We could handle that and show an information to the user that the contract is not declared to the network at all.

**Comment by integraledelebesgue** [comment]
I added a workaround for preserving old error messages despite throwing them from completely other place. `ContractError`s normally obtained *after* sending transaction to chain is created [here](https://github.com/foundry-rs/starknet-foundry/blob/bd568166c8636ef7d0f80b179f9de44f9efef77e/crates/sncast/src/lib.rs#L278) and [here](https://github.com/foundry-rs/starknet-foundry/blob/bd568166c8636ef7d0f80b179f9de44f9efef77e/crates/sncast/src/lib.rs#L478) to mimic the old behaviour.
This isn't a nice solution though. I think that our error handling logic may need a revamp.

**Comment by integraledelebesgue** [comment]
See [#2572](https://github.com/foundry-rs/starknet-foundry/issues/2572)

**Comment by cptartur** [comment]
The workarounds introduced to solve this might no longer be required/good since we are distinguishing data transformation and old calldata flow.

**Comment by cptartur** [comment]
Closing in favor of #2694
