### ISSUE TITLE
Remove usage od deprectaed `LegacyMap`

### ISSUE THREAD

**Issue by franciszekjob** [foundry-rs/starknet-foundry#2598]
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

In some places in packages in `crates/forge/tests/data` we're still using deprecated `LegacyMap`. We should update it to use `starknet::storage::Map` instead.

Example usages:
https://github.com/foundry-rs/starknet-foundry/blob/8df49f64d420740e1b946f68ec7c414af77aca0e/crates/sncast/tests/data/scripts/map_script/contracts/src/lib.cairo#L13

https://github.com/foundry-rs/starknet-foundry/blob/8df49f64d420740e1b946f68ec7c414af77aca0e/crates/forge/tests/data/component_macros/src/oz_ac_component.cairo#L18

**Comment by sprtd** [comment]
I'd be glad to work on this issue. Could you please assign it to me?

**Comment by ryzen-xp** [comment]
Hello @franciszekjob , 
            Please  assign this issue  to me .

**Comment by cptartur** [comment]
This issue is reserved for ODHack. Please apply through the page as outlined there after the hack starts 
https://app.onlydust.com/hackathons/odhack-90

**Comment by gsbujo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry2).

### My background and how it can be leveraged
Hello, 
I started learning blockchain programming 2 years ago in my free time. I would like to continue my learning by contributing to open source projects. I'm also very excited to learn the different github workflows related to open source contribution. I have a first experience in Cairo via Node Guardians and BaseCampX.

### How I plan on tackling this issue
I'll fork the repository, run the tests first to see if everything is ok. Then I'll find and replace the LegacyMap instance with the Map (and update the crates to use). Run the test and fix any issues if there are any.

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry2).

### My background and how it can be leveraged
Hi @franciszekjob, I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working on ByteBeasts, a fully on-chain RPG game built using the Dojo Engine framework.

### How I plan on tackling this issue
- I’ll locate all instances of LegacyMap in the mentioned files and update them to use starknet::storage::Map.
- After making the changes, I’ll run tests to ensure everything works correctly.
- I’ll also check for any other occurrences of LegacyMap in the codebase to ensure a complete update.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.


### How I plan on tackling this issue
To resolve this issue, I will identify all instances where the deprecated `LegacyMap` is still being used within the affected packages, particularly in the `snforge` directory. I will replace these usages with the newer `starknet::storage::Map` type. This change will involve updating the imports, as well as modifying the syntax where `LegacyMap` is used in contracts, tests, and scripts. Specifically, I will refactor instances like `storage: LegacyMap::<felt252, felt252>` and `SRC5_supported_interfaces: LegacyMap<felt252, bool>` to use the new `Map` type. Once the refactor is complete, I will ensure that all tests pass by running the test suite and verifying that no functionality is broken due to the update.

ETA- 1 day

**Comment by enehizy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hi my name is Osas, I am a Cairo and Javascript Developer , I love to contribute to projects like this because I use them everyday and really love and appreciate them

### How I plan on tackling this issue
I would go through all the files and with the help of my language server find and change the legacy map to naps an the I would compile and test the codebase

**Comment by DanielEmmanuel1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hello again, My name is Deon and I am a Full-Stack Web3 developer with sufficient experience building web3 applications/smart contracts with Rust, as well as high-performance backends. 

I have a solid understanding of both backend development and data management which I believe makes me qualified to tackle this issue.

### How I plan on tackling this issue
- Firstly I’ll review the code in crates/forge/tests/data to locate all instances of LegacyMap usage.

- Then I’ll replace with starknet::storage::Map: Update each occurrence to use starknet::storage::Map instead, ensuring that the new implementation aligns with the intended functionality.

- I’ll then run the existing test suite to verify that all tests pass after the changes, ensuring that the refactoring did not introduce any issues.

- Then If necessary, update any related documentation to reflect the changes made during the update.

I believe by following these steps, I will modernize the codebase, enhancing compatibility and ensuring that we are using the most current practices.

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement and i've had experience upgrading contracts to the latest versions of Cairo.

### How I plan on tackling this issue
I'll refactor the necessary aspect of the repo and ensure no existing functionality/test are broken.

**Comment by khayss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I am a Rust developer with a solid background in blockchain technology and experience contributing to various projects. My proficiency with Rust has been honed through multiple projects where I worked on optimizing performance and ensuring code sustainability. I’m passionate about contributing to open-source initiatives, especially those that drive innovation in blockchain, like Starknet Foundry.

### How I plan on tackling this issue
To address the issue of removing the deprecated `LegacyMap` from the codebase, I plan to:

1. Identify all occurrences of `LegacyMap` within the `crates/forge/tests/data` package.
2. Refactor each instance, replacing `LegacyMap` with the updated `starknet::storage::Map`.
3. Run the existing tests to ensure that all functionality remains intact after the refactor.
4. Implement any additional test cases if necessary to cover edge cases specific to the `starknet::storage::Map` usage.
5. Conduct a thorough review of the changes to ensure compatibility and correctness across the package.

I’m excited about the opportunity to contribute to Starknet Foundry and would love to be considered for this issue.

---

Let me know if you'd like any tweaks!

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
GM @kkawula, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, JavaScript and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo and Rust languages. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
 - I found 14 instances where `LegacyMap` has been used across the codebase. I will replace each and every one of them to use `Map` instead, from `starknet::storage::Map`
 - Test the codebase by running and make sure no errors arise.
 - Create the PR

## ETA: 1 Day

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue, I’ll take the following steps:
1.⁠ ⁠I’ll have to first identify all instances of LegacyMap in the codebase, particularly in test and contract files under crates/forge/tests/data and crates/sncast/tests/data.
2.⁠ ⁠⁠Then replace LegacyMap with starknet::storage::Map in all occurrences. Mappings like:
LegacyMap::<felt252, felt252> → starknet::storage::Map::<felt252, felt252>
For boolean maps: LegacyMap::<felt252, bool> → starknet::storage::Map::<felt252, bool>. 
3.⁠ ⁠Next, I’ll update imports to include starknet::storage::Map where necessary. I’ll also clean up any deprecated code related to LegacyMap after the transition is complete.
4.⁠ ⁠⁠Lastly, i’ll run tests to ensure the changes work correctly.

Please assign me, I’m ready to work.

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hello, I’m Jose Mario from Costa Rica. With over 15 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity, participated in ODHacks since 7.0 as part of my involvement with Dojo Coding. I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
. Locate all instances of LegacyMap and replace with starknet::storage::Map
. Ensure that all method calls used with LegacyMap are compatible with Map, adjusting as necessary
. Run tests to verify that everything works correctly after the changes

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
Hello, can I be assigned to work on this issue?

I'm a software developer with over 4 years experience

Here's my OnlyDust profile https://app.onlydust.com/u/raizo07

ETA: One day

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
i have experience in cairo and blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution

### How I plan on tackling this issue
I'll approach the LegacyMap modernization systematically across both crates/forge/tests/data and crates/sncast/tests/data directories, with special focus on component_macros and map_script contract tests, while implementing a validation script to ensure we catch any deeply nested instances that standard searches might miss.

**Comment by TropicalDog17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-foundry).

### My background and how it can be leveraged
I am an experienced Rust dev and have experience working on various open sources projects.

I've implemented a cheatcode in the foundry repo: https://github.com/foundry-rs/foundry/pull/8258/



### How I plan on tackling this issue
I will find all instances of LegacyMap and update it to use starknet::storage::Map instead, and I will make sure the tests will passing and the replacement won't break things.
