### ISSUE TITLE
`available_gas` support in forge

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#618]
We should support the attribute in test collector and enforce it in the runner

**Comment by piotmag769** [comment]
I belive it should work out of the box

**Comment by Arcticae** [comment]
Please do this one before:
[995](https://github.com/foundry-rs/starknet-foundry/issues/995)

**Comment by piotmag769** [comment]
It requires changing the scarb test collector for sure

**Comment by piotmag769** [comment]
Currently we don't allow such attribute to be defined

**Comment by piotmag769** [comment]
https://github.com/software-mansion/scarb/blob/main/extensions/scarb-snforge-test-collector/src/compilation/test_collector/config.rs#L117

Just remove this line and below https://github.com/software-mansion/scarb/blob/main/extensions/scarb-snforge-test-collector/src/compilation/test_collector/config.rs#L160 reuse the available gas from `try_extract_test_config` (it will be set to some large value if there is no `available_gas` attribute, that's why I set it to a random `Some` value before to indicate it was used when it was not meant to)

**Comment by Arcticae** [comment]
Should be limited to the original scope (see description)
