### ISSUE TITLE
 Issue on Creating and Deploying Accounts Section of Documentation

### ISSUE THREAD

**Issue by timothyAgevi** [foundry-rs/starknet-foundry#626]
### Which component is your bug related to?

Cast

### Foundry Version

0.5.0

### What operating system are you using?

Linux

### What system architecture are you using?

x86

### What happened

when you run the below command, it fails to work as expected

```sh
sncast \
  --url http://127.0.0.1:5050 \
  account create \
  --name some-name
```

Expected: Account created successfully

### Trace

Error 

```sh
command: account create
error: JSON-RPC error: code=-1, message="Class with hash 0x58d97f7d76e78f44905cc30cb65b91ea49a4b908a76703c54197bca90f81773 is not declared."
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by THenry14** [comment]
Hi @timothyAgevi , I can see you are using a local devnet right? Please note that devnet have different class hashes than integration/testnet/mainnet, and you should provide a proper class hash to sncast in order to be able to create an account. You can consult devnet docs to see what class hash to use.

**Comment by THenry14** [comment]
Closing as it is not a scnast bug.
