### ISSUE TITLE
Mapping Cairo function -> Sierra

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#846]
Investigate and contribute to cairo1 compiler, so we can map cairo code to sierra code. This will be useful for advanced fuzzer, gas profiling, debugging, test coverage etc.

**Comment by MaksymilianDemitraszek** [comment]
Moved to cairo-profiler effort

**Comment by MaksymilianDemitraszek** [comment]
This is already done by the compiler team, we only have to expose this in scarb.

**Comment by piotmag769** [comment]
Postponing it for now since we don't need it for function level profiling - Sierra contains all info that we need.
Will investigate it after making the MVP using Sierra to make profiler independent from Sierra version.
Then after having Cairo -> Sierra mapping we can use the Sierra -> CASM mapping (easy to generate, code for it is in the compiler and will be in the profiler too) to generate Cairo -> CASM mappings.

**Comment by piotmag769** [comment]
Done in both compiler and scarb
